### ISSUE TITLE
Cannot replicate example in Advanced User Guide

### ISSUE THREAD

**Issue by Hellofafar** [usc-isi-i2/dig-etl-engine#126] opened 2017-12-03 00:00 UTC
Hi,

I cannot complete the example in Advanced User Guide (events project)

After I imported the project and dataset, then clicked  "recreate knowledge graph". But there is no change after waiting for 15 mins.

<img width="1001" alt="screen shot 2017-12-02 at 3 58 09 pm" src="https://user-images.githubusercontent.com/24971983/33520957-a692055a-d779-11e7-83d0-564c6cad1efa.png">

<img width="636" alt="screen shot 2017-12-02 at 3 58 42 pm" src="https://user-images.githubusercontent.com/24971983/33520961-ba3784b8-d779-11e7-888c-a5e0006b5917.png">

I pulled mydig project today so I wonder if it's because of reverting version?

**Comment by GreatYYX** [comment] 2017-12-03 08:09
What's in you `PROJECT_FOLDER/<project_name>/working_dir/etk_stdout_*.txt`?

**Comment by Hellofafar** [comment] 2017-12-03 08:45
There are etk_stdout_0.txt and etk_stdout_1.txt, but both are empty file.
<img width="248" alt="screen shot 2017-12-03 at 12 44 02 am" src="https://user-images.githubusercontent.com/24971983/33523762-3eddbcf2-d7c3-11e7-8956-5fa09aeaff56.png">

**Comment by GreatYYX** [comment] 2017-12-03 09:01
After clicking recreate button, have you seen any error in alert box? Have you given enough memory? 
Any errors in Kafka `docker logs dig_kafka_1`?
Try to increase the heap size of Kafka in docker-compose: e.g., locate to kafka section, increase heap size from 256m to 1g.

**Comment by GreatYYX** [comment] 2017-12-03 09:03
Please also paste your `docker ps -a` result here

**Comment by Hellofafar** [comment] 2017-12-03 09:13
No I didn't see any alert. I gave 6G memory to docker.

I see a WARN: Unable to reconnect to ZooKeeper service, session 0x160199d7c7f0005 has expired (org.apache.zookeeper.ClientCnxn) in Kafka logs.
[logs.txt](https://github.com/usc-isi-i2/dig-etl-engine/files/1524606/logs.txt)

As for docker ps -a: 
<img width="1279" alt="screen shot 2017-12-03 at 1 12 48 am" src="https://user-images.githubusercontent.com/24971983/33523923-250f65e2-d7c7-11e7-8068-2653e2a68774.png">

**Comment by Hellofafar** [comment] 2017-12-04 02:06
Hi,

I just removed all the containers and images, then restart from scratch. It seems it works now and completes building the knowledge graph.

![image](https://user-images.githubusercontent.com/24971983/33533185-5a06c71c-d854-11e7-8df1-0112513fa237.png)

But I also tracked an error, I'm not sure if it's important.
<img width="636" alt="screen shot 2017-12-03 at 6 02 08 pm" src="https://user-images.githubusercontent.com/24971983/33533250-afc6e812-d854-11e7-903f-ca428fae0336.png">

**Comment by GreatYYX** [comment] 2017-12-04 07:43
This problem comes when session timeout max time is not enough for current environment which includes the size of (batched) doc, not enough memory for Zookeeper / Kafka, etc. 
You may need to fine tune Kafka configs in section of Kafka in docker-compose.yml and PROJECT_DIR/<project_name>/working_dir/etl_config.json. We currently don't have document for it. But you can ignore it right now, it will just take long time to process.

**Comment by GreatYYX** [comment] 2017-12-13 02:43
Closing, please reopen it if the issue is still there.

**Closed by GreatYYX** 2017-12-13 02:43 UTC
